import { type NextPage } from "next";
import Head from "next/head";
import ImageIndex from '../components/ImageIndex';


const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>ConnectMe</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/global-network.png" />
      </Head>
      <div>

      <ImageIndex />


    </div>
    </>
    
  );
};

export default Home;


