import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Logo from "../components/Logo";
import Login from "../components/Login";
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";
import { getServerAuthSession } from "~/server/auth";


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>ConnectMe</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/global-network.png" />
      </Head>

      <div className="grid h-screen grid-cols-2 gap-0 bg-gray-200">
        <Logo />
        <Login />
      </div>
    </>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getServerAuthSession(context);
  if (session) return { redirect: {destination: "/server", permanent: true}};
  return {
    props: {},
  };
};
